### ISSUE TITLE
Wish: to be able to pull and run the tool using docker

### ISSUE THREAD

**Issue by mskyttner** [Inkimar/commons_cli_ex#7]
An Alpine based image with the acess2csv tool available on Docker hub.

Perhaps this distribution could be based on openjdk:8-jre-alpine from Docker Hub - it would be nice, portable and a simple install.

It could support usage when mobilizing data from old Access databases to other formats via CSV exports in the following way:

```
# download the tool
docker pull inkimar/access2csv

# running it without options will display available options and inform about usage
docker run --rm inkimar/access2csv 

# example usage running a conversion of an access db into CSV files which are stored in the "output" destination directory
docker run --rm inkimar/access2csv -f my_access_db.mdb -d output
```

**Comment by Inkimar** [comment]
Docker support is in the project https://github.com/bioatlas/access2csv-docker
